# Configuration for the macOS Virtualization.Framework driver

# The default driver directory for VM configs
driver_dir = "@localstatedir@/lib/libvirt/macosvf"

# Whether to allow VMs to start automatically on libvirtd startup
#auto_start = 1

# Maximum number of VCPUs allowed per VM
#max_vcpus = 4

# Default memory allocation (in KB)
#default_memory = 1048576
